### ISSUE TITLE
Could you release the voxelization and evaluation on IOU?

### ISSUE THREAD

**Issue by xiaomingjie** [justanhduc/graphx-conv#6]
Hi @justanhduc ,

The paper mentioned that you voxelized the point sets into a 32 × 32 × 32 grid and calculated the scores but I couldn't find the corresponding code here. Could you release the voxelization and evaluation on IOU?

Thank you.

**Comment by justanhduc** [comment]
Hi. I didn't put it here cuz [it was in Tensorflow](https://github.com/eldar/differentiable-point-clouds/blob/d9b6725db6ef1d66a456486040a17ffc987ebaa2/dpc/util/point_cloud.py#L60). I ported the code to pytorch [here](https://gist.github.com/justanhduc/514ed66db6a3bcc953151cf4a4c391b2). Please check. Thanks.

**Comment by xiaomingjie** [comment]
Thanks very much.
