### ISSUE TITLE
how to generate the train/test data

### ISSUE THREAD

**Issue by ywcmaike** [justanhduc/graphx-conv#7]
I have downloaded the dataset from pixel2mesh, but the file is organized like "ShapeNetP2M/04256520/cc32fde4ca022cdf965e01bcaa1587c5/rendering/02.dat" but not like "02691156_d004d0e86ea3d77a65a6ed5c458f6a32_00.dat"  as you saided.

I run the split.py and will received the bug:
Traceback (most recent call last):
  File "split.py", line 34, in <module>
    if os.path.exists(class_path + tr_data):
NameError: name 'class_path' is not defined
it means you don't provide the complete code of the data generation.

and then i try to look the .dat provided by pix2mesh, 
>>> contents = pkl.load(open('00.dat', 'rb'), encoding='latin1')
>>> contents.shape
(8307, 6)
but not as the dataloader.py  you provide
        contents = pkl.load(open(pkl_path, 'rb'), encoding='latin1')
        img = rgb2gray(contents[0])[..., None] if self.grayscale else contents[0]
        img = (np.transpose(img / 255.0, (2, 0, 1)) - .5) * 2
        pc = np.array(contents[1], 'float32')[:, :3]
        pc -= np.mean(pc, 0, keepdims=True)

I want to know if you add the img to the .dat of pix2mesh and produce the new .dat file,   Can you provide the complete code, I want to try your code. thanks
@justanhduc

**Comment by justanhduc** [comment]
Please use our processed db [here](https://drive.google.com/open?id=1EzGkZ4XBhVNGZPnMXPSbkOaNz2sechbZ).

**Comment by NaveedMaz** [comment]
hi,
@ywcmaike how did you open the shapenetP2M what's the password i really need that dataset but the problem is that official repo holders are not responding. please help

**Comment by justanhduc** [comment]
hi @NaveedMaz. I don't remember there is any password to extract the 7zip files from Pixel2Mesh repo.

**Comment by AntinomiK** [comment]
> Please use our processed db [here](https://drive.google.com/open?id=1EzGkZ4XBhVNGZPnMXPSbkOaNz2sechbZ).

Hi. I'm not able to open this link. Could you provide me with an alternative? I'd appreciate it

**Comment by justanhduc** [comment]
Hi @AntinomiK. Please try [this link](https://yonsei-my.sharepoint.com/:u:/g/personal/adnguyen_o365_yonsei_ac_kr/Ee-OcT0WRthJq2GvBi8HKZ0BEOyOXOmJ9JPYAB0NbqmjEg?e=4QljKW).

**Comment by AntinomiK** [comment]
Hi !!!
Thanks a lot for your information!
May I ask about a problem occurred?
So what I’ve downloaded was Shapenet.tar.gz
At first, I tried to decompress the gz and there comes the tar file.
And After I tried to decompress the tar file, another tar file was created as a result.

Later I tried to download it again and found that the safari is automatically decompressing the file as soon as it is downloaded, but error occurs all the time and tells that the process falied.
It seems odd. I’ve downloaded it for more than  10 times…..
Could you please provide me with some hints or explanation of these problems?
I’d appreciate your reply.

Sincerely,
AntinomiK
(A university student majoring in SE learning from your paper)
